appName: hello-web
version: 0.0.1
development: true
log:
  cores:
    - level: debug
      disableCaller: true
      disableStacktrace: true
      encoding: json
      outputPaths:
        - stdout
        - "logs/test.log"
      errorOutputPaths:
        - stderr
  rotate:
    maxSize: 1
    maxage: 1
    maxbackups: 1
    localtime: true
    compress: false
web:
  server:
    addr: 0.0.0.0:33333
  engine:
    routerGroups:
      - default:
          middlewares:
            - otel:
            - accessLog:
                format: id,remoteIp,host,method,uri,userAgent,status,error,latency,bytesIn,bytesOut,header:Cache-Control
                exclude:
                  - IntrospectionQuery
            - recovery:
otel:
  traceExporterEndpoint: "http://localhost:9411/api/v2/spans"
  metricExporterEndpoint: prometheus