namespace: default
appName: adminx
version: 0.0.1
development: true
log:
  cores:
    - level: debug
service:
  server:
    addr: 127.0.0.1:0
    version: "1.0"
    engine:
      - unaryInterceptors:
          - recovery:
    registryMeta:
      location: default
  registry:
    ref: registry
    scheme: polaris
  client:
    target:
      metadata:
        version: "1.0"
        route: true
        dst_location: amoy
        src_country: CN
        circuitBreaker: true
    dialOption:
      - tls:
      - block:
      - timeout: 10s

registry:
  scheme: polaris
  ttl: 30s # 设置心跳健康检查ttl，单位为s，不填默认为5s，TTL的取值范围为 (0s, 60s]
  polaris:
    global:
      serverConnector:
        addresses:
          - 127.0.0.1:8091
      statReporter:
        enable: true
        chain:
          - prometheus
        #        - pushgateway
        plugin:
          prometheus:
            type: pull
            metricPort: 0
